// components/master/locations/mockData.ts
import { Location } from "./types";

export const mockLocations: Location[] = [
  {
    id: "1",
    code: "MUM-CENTRAL",
    name: "Mumbai Central Hub",
    type: "hub",
    address: "78 Andheri East, Near International Airport",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400069",
    contactPerson: "Rajesh Kumar",
    phone: "022-12345678",
    email: "mumbai.hub@logistics.com",
    capacity: {
      shipments: 5000,
      storage: 10000,
      vehicles: 45,
    },
    facilities: [
      "Sorting",
      "Storage",
      "Vehicle Maintenance",
      "Security",
      "CCTV",
    ],
    operatingHours: {
      open: "06:00",
      close: "22:00",
      workingDays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
    },
    services: ["Express Delivery", "COD", "Reverse Logistics", "Bulk Handling"],
    status: "active",
    manager: "Priya Sharma",
    coordinates: {
      lat: 19.076,
      lng: 72.8777,
    },
    isOperational: true,
    lastAudit: "2024-11-15",
    nextAudit: "2025-02-15",
    securityLevel: "high",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-11T08:30:00Z",
  },
  {
    id: "2",
    code: "DEL-NORTH",
    name: "Delhi North Warehouse",
    type: "warehouse",
    address: "45 Nehru Place, Industrial Area",
    city: "Delhi",
    state: "Delhi",
    pincode: "110019",
    contactPerson: "Amit Singh",
    phone: "011-23456789",
    email: "delhi.warehouse@logistics.com",
    capacity: {
      shipments: 3000,
      storage: 8000,
      vehicles: 25,
    },
    facilities: ["Storage", "Packaging", "Quality Check", "Forklifts"],
    operatingHours: {
      open: "08:00",
      close: "20:00",
      workingDays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
    },
    services: ["Storage", "Packaging", "Inventory Management"],
    status: "active",
    manager: "Rohit Verma",
    coordinates: {
      lat: 28.6139,
      lng: 77.209,
    },
    isOperational: true,
    lastAudit: "2024-10-20",
    nextAudit: "2025-01-20",
    securityLevel: "medium",
    createdAt: "2024-02-20T14:30:00Z",
    updatedAt: "2024-12-11T09:15:00Z",
  },
  {
    id: "3",
    code: "BLR-SOUTH",
    name: "Bangalore South Counter",
    type: "counter",
    address: "23 Koramangala, 5th Block",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560034",
    contactPerson: "Sneha Patel",
    phone: "080-34567890",
    email: "bangalore.counter@logistics.com",
    capacity: {
      shipments: 500,
      storage: 200,
      vehicles: 5,
    },
    facilities: ["Customer Service", "Payments", "Parcel Drop-off"],
    operatingHours: {
      open: "09:00",
      close: "21:00",
      workingDays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
    },
    services: ["Parcel Booking", "COD Collection", "Customer Support"],
    status: "active",
    manager: "Kiran Reddy",
    coordinates: {
      lat: 12.9716,
      lng: 77.5946,
    },
    isOperational: true,
    lastAudit: "2024-12-01",
    nextAudit: "2025-03-01",
    securityLevel: "medium",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-12-10T16:45:00Z",
  },
  {
    id: "4",
    code: "CHE-PROC",
    name: "Chennai Processing Center",
    type: "processing_center",
    address: "34 Guindy Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    contactPerson: "Vikram Joshi",
    phone: "044-45678901",
    email: "chennai.processing@logistics.com",
    capacity: {
      shipments: 2000,
      storage: 5000,
      vehicles: 18,
    },
    facilities: ["Sorting", "Scanning", "Quality Control", "Data Processing"],
    operatingHours: {
      open: "07:00",
      close: "23:00",
      workingDays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
    },
    services: ["Sorting", "Scanning", "Quality Check", "Data Entry"],
    status: "maintenance",
    manager: "Arun Kumar",
    coordinates: {
      lat: 13.0827,
      lng: 80.2707,
    },
    isOperational: false,
    lastAudit: "2024-09-25",
    nextAudit: "2024-12-25",
    securityLevel: "high",
    createdAt: "2024-04-05T11:00:00Z",
    updatedAt: "2024-12-11T10:20:00Z",
  },
  {
    id: "5",
    code: "HYD-OFFICE",
    name: "Hyderabad Regional Office",
    type: "office",
    address: "12 Banjara Hills, Road No. 1",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500034",
    contactPerson: "Anjali Mehta",
    phone: "040-56789012",
    email: "hyderabad.office@logistics.com",
    capacity: {
      shipments: 100,
      storage: 50,
      vehicles: 2,
    },
    facilities: ["Admin", "Meeting Rooms", "Training Center"],
    operatingHours: {
      open: "09:00",
      close: "18:00",
      workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    },
    services: ["Administration", "Training", "Coordination"],
    status: "active",
    manager: "Sanjay Gupta",
    coordinates: {
      lat: 17.385,
      lng: 78.4867,
    },
    isOperational: true,
    lastAudit: "2024-11-30",
    nextAudit: "2025-02-28",
    securityLevel: "medium",
    createdAt: "2024-05-15T13:00:00Z",
    updatedAt: "2024-12-11T11:30:00Z",
  },
  {
    id: "6",
    code: "KOL-WEST",
    name: "Kolkata West Warehouse",
    type: "warehouse",
    address: "56 Salt Lake, Sector V",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700091",
    contactPerson: "Bikram Das",
    phone: "033-67890123",
    email: "kolkata.warehouse@logistics.com",
    capacity: {
      shipments: 2500,
      storage: 6000,
      vehicles: 20,
    },
    facilities: ["Storage", "Inventory Management", "Security"],
    operatingHours: {
      open: "07:30",
      close: "19:30",
      workingDays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
    },
    services: ["Storage", "Inventory Management", "Bulk Handling"],
    status: "inactive",
    manager: "Partha Roy",
    coordinates: {
      lat: 22.5726,
      lng: 88.3639,
    },
    isOperational: false,
    lastAudit: "2024-08-15",
    nextAudit: "2024-11-15",
    securityLevel: "medium",
    createdAt: "2024-06-20T15:00:00Z",
    updatedAt: "2024-12-10T14:15:00Z",
  },
];
