// @/components/booking/create/mockData.ts
import { Customer } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "1",
    code: "YELLOWRAJAST",
    documentNo: "123456",
    name: "YELLOW THREAD INDIA PRIVATE LIMITED",
    contactPerson: "Rajesh Kumar",
    address1: "PLOT NO 29, MIG PHASE 1",
    address2: "VANASTHALIPURAM",
    city: "JAIPUR",
    station: "RANGA REDDY",
    pincode: "500070",
    gstin: "36AAACY4430D1ZN",
    mobileNo: "9876543210",
    phoneO: "0141-1234567",
    phoneR: "0141-1234568",
    email: "info@yellowthread.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-1",
        name: "Amit Sharma",
        address: "Shop No 45, Market Complex",
        city: "Mumbai",
        pincode: "400001",
        mobileNo: "9876543211",
        email: "amit@yellowthread.com",
      },
      {
        id: "rec-2",
        name: "Priya Singh",
        address: "Office No 12, Business Park",
        city: "Delhi",
        pincode: "110001",
        mobileNo: "9876543212",
        email: "priya@yellowthread.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-1",
        name: "Main Warehouse",
        address: "Warehouse No 5, Industrial Area",
        city: "Jaipur",
        pincode: "302022",
        contactPerson: "Ramesh Kumar",
        mobileNo: "9876543213",
      },
      {
        id: "pickup-2",
        name: "Branch Office",
        address: "First Floor, Business Center",
        city: "Jaipur",
        pincode: "302015",
        contactPerson: "Suresh Mehta",
        mobileNo: "9876543214",
      },
    ],
    status: "active",
    // New Master Data Fields
    allowedServices: ["SURFACE", "AIR", "EXPRESS"],
    serviceableZones: ["ALL"],
    riskStatus: "LOW",
    creditLimit: 50000,
    paymentMode: "CREDIT" // Default PREFERENCE
  },
  {
    id: "2",
    code: "BLUETEX",
    documentNo: "451220",
    name: "BLUE TEXTILES LIMITED",
    contactPerson: "Priya Sharma",
    address1: "UNIT 45, INDUSTRIAL AREA",
    address2: "SITAPURA",
    city: "JAIPUR",
    station: "JAIPUR",
    pincode: "302022",
    gstin: "08AABCU9603R1ZN",
    mobileNo: "9876543211",
    phoneO: "0141-2345678",
    phoneR: "0141-2345679",
    email: "accounts@bluetex.com",
    hasReceiver: false,
    receivers: [],
    usePickupLocation: false,
    pickupLocations: [],
    status: "active",
  },
  {
    id: "3",
    code: "GREENFIB",
    documentNo: "136909",
    name: "GREEN FIBERS CORPORATION",
    contactPerson: "Amit Patel",
    address1: "BLOCK B, SECTOR 25",
    address2: "MALVIYA NAGAR",
    city: "DELHI",
    station: "DELHI",
    pincode: "110017",
    gstin: "07AABCU9603R1ZN",
    mobileNo: "9876543212",
    phoneO: "011-3456789",
    phoneR: "011-3456790",
    email: "operations@greenfib.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-3",
        name: "Sanjay Verma",
        address: "Godown No 8, Transport Nagar",
        city: "Gurgaon",
        pincode: "122001",
        mobileNo: "9876543214",
        email: "sanjay@greenfib.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-3",
        name: "Factory Unit",
        address: "Unit 15, SEZ Area",
        city: "Delhi",
        pincode: "110020",
        contactPerson: "Vikram Singh",
        mobileNo: "9876543215",
      },
    ],
    status: "inactive",
  },
];

export const paymentModes = [
  { value: "cash", label: "Cash" },
  { value: "credit", label: "Credit" },
  { value: "online", label: "Online" },
  { value: "cod", label: "COD" },
];
