// @/components/booking/create/mockData.ts
import { Customer } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "1",
    code: "YELLOWRAJAST",
    documentNo: "123456",
    name: "YELLOW THREAD INDIA PRIVATE LIMITED",
    contactPerson: "Rajesh Kumar",
    address1: "PLOT NO 29, MIG PHASE 1",
    address2: "VANASTHALIPURAM",
    city: "JAIPUR",
    station: "RANGA REDDY",
    pincode: "500070",
    gstin: "36AAACY4430D1ZN",
    mobileNo: "9876543210",
    phoneO: "0141-1234567",
    phoneR: "0141-1234568",
    email: "info@yellowthread.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-1",
        name: "Amit Sharma",
        address: "Shop No 45, Market Complex",
        city: "Mumbai",
        pincode: "400001",
        mobileNo: "9876543211",
        email: "amit@yellowthread.com",
      },
      {
        id: "rec-2",
        name: "Priya Singh",
        address: "Office No 12, Business Park",
        city: "Delhi",
        pincode: "110001",
        mobileNo: "9876543212",
        email: "priya@yellowthread.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-1",
        name: "Main Warehouse",
        address: "Warehouse No 5, Industrial Area",
        city: "Jaipur",
        pincode: "302022",
        contactPerson: "Ramesh Kumar",
        mobileNo: "9876543213",
      },
      {
        id: "pickup-2",
        name: "Branch Office",
        address: "First Floor, Business Center",
        city: "Jaipur",
        pincode: "302015",
        contactPerson: "Suresh Mehta",
        mobileNo: "9876543214",
      },
    ],
    status: "active",
  },
  {
    id: "2",
    code: "BLUETEX",
    documentNo: "451220",
    name: "BLUE TEXTILES LIMITED",
    contactPerson: "Priya Sharma",
    address1: "UNIT 45, INDUSTRIAL AREA",
    address2: "SITAPURA",
    city: "JAIPUR",
    station: "JAIPUR",
    pincode: "302022",
    gstin: "08AABCU9603R1ZN",
    mobileNo: "9876543211",
    phoneO: "0141-2345678",
    phoneR: "0141-2345679",
    email: "accounts@bluetex.com",
    hasReceiver: false,
    receivers: [],
    usePickupLocation: false,
    pickupLocations: [],
    status: "active",
  },
  {
    id: "3",
    code: "GREENFIB",
    documentNo: "136909",
    name: "GREEN FIBERS CORPORATION",
    contactPerson: "Amit Patel",
    address1: "BLOCK B, SECTOR 25",
    address2: "MALVIYA NAGAR",
    city: "DELHI",
    station: "DELHI",
    pincode: "110017",
    gstin: "07AABCU9603R1ZN",
    mobileNo: "9876543212",
    phoneO: "011-3456789",
    phoneR: "011-3456790",
    email: "operations@greenfib.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-3",
        name: "Sanjay Verma",
        address: "Godown No 8, Transport Nagar",
        city: "Gurgaon",
        pincode: "122001",
        mobileNo: "9876543214",
        email: "sanjay@greenfib.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-3",
        name: "Factory Unit",
        address: "Unit 15, SEZ Area",
        city: "Delhi",
        pincode: "110020",
        contactPerson: "Vikram Singh",
        mobileNo: "9876543215",
      },
    ],
    status: "inactive",
  },
  {
    id: "4",
    code: "REDMETAL",
    documentNo: "789012",
    name: "RED METAL WORKS",
    contactPerson: "Sanjay Gupta",
    address1: "SECTOR 18, INDUSTRIAL ESTATE",
    address2: "OKHLA",
    city: "DELHI",
    station: "DELHI",
    pincode: "110020",
    gstin: "07AABCU9603R1ZO",
    mobileNo: "9876543216",
    phoneO: "011-4567890",
    phoneR: "011-4567891",
    email: "sales@redmetal.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-4",
        name: "Rohit Malhotra",
        address: "Showroom No 5, Main Market",
        city: "Noida",
        pincode: "201301",
        mobileNo: "9876543217",
        email: "rohit@redmetal.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-4",
        name: "Head Office",
        address: "Building No 10, Corporate Park",
        city: "Delhi",
        pincode: "110025",
        contactPerson: "Neha Kapoor",
        mobileNo: "9876543218",
      },
    ],
    status: "active",
  },
  {
    id: "5",
    code: "WHITECHEM",
    documentNo: "345678",
    name: "WHITE CHEMICALS INDIA",
    contactPerson: "Anita Desai",
    address1: "PLOT NO 56, CHEMICAL ZONE",
    address2: "ANKAleshwar",
    city: "ANKAleshwar",
    station: "GUJARAT",
    pincode: "393010",
    gstin: "24AABCU9603R1ZP",
    mobileNo: "9876543219",
    phoneO: "02646-123456",
    phoneR: "02646-123457",
    email: "info@whitechemicals.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-5",
        name: "Mahesh Patel",
        address: "Warehouse Complex, GIDC",
        city: "Vapi",
        pincode: "396195",
        mobileNo: "9876543220",
        email: "mahesh@whitechemicals.com",
      },
      {
        id: "rec-6",
        name: "Sunil Reddy",
        address: "Distribution Center, Phase 2",
        city: "Hyderabad",
        pincode: "500072",
        mobileNo: "9876543221",
        email: "sunil@whitechemicals.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-5",
        name: "Main Plant",
        address: "GIDC Estate, Phase 3",
        city: "Ankleshwar",
        pincode: "393002",
        contactPerson: "Rajiv Mehta",
        mobileNo: "9876543222",
      },
    ],
    status: "active",
  },
];

export const paymentModes = [
  { value: "cash", label: "Cash" },
  { value: "credit", label: "Credit" },
  { value: "online", label: "Online" },
  { value: "cod", label: "COD" },
];
