import { Partner, PartnerStat } from "./types";
import { Users, CheckCircle, Clock, IndianRupee } from "lucide-react";

export const partnerStats: PartnerStat[] = [
    {
        title: "Total Partners",
        value: "248",
        change: "+12",
        trend: "up",
        icon: Users,
        description: "Active partnerships",
    },
    {
        title: "Active Partners",
        value: "235",
        change: "+8",
        trend: "up",
        icon: CheckCircle,
        description: "Currently operating",
    },
    {
        title: "Pending Approvals",
        value: "13",
        change: "+5",
        trend: "down",
        icon: Clock,
        description: "Awaiting review",
    },
    {
        title: "Revenue Share",
        value: "₹125.8L",
        change: "+15.2%",
        trend: "up",
        icon: IndianRupee,
        description: "This month",
    },
];

export const partnerData: Partner[] = [
    {
        id: "PTR-001",
        name: "Spice Garden Restaurant",
        partnerId: "SGR-2024-001",
        type: "restaurant",
        location: "Sector 18, Noida",
        city: "Noida",
        status: "active",
        performanceScore: 94,
        totalRevenue: 2850000,
        monthlyRevenue: 285000,
        joinDate: "2023-03-15",
        contactPerson: "Rajesh Kumar",
        phone: "+91 98765 43210",
        email: "rajesh@spicegarden.com",
        deliveryRadius: 5,
        avgRating: 4.7,
    },
    {
        id: "PTR-002",
        name: "FreshMart Grocery",
        partnerId: "FMG-2024-002",
        type: "grocery",
        location: "Connaught Place, Delhi",
        city: "Delhi",
        status: "active",
        performanceScore: 88,
        totalRevenue: 1950000,
        monthlyRevenue: 195000,
        joinDate: "2023-06-20",
        contactPerson: "Priya Sharma",
        phone: "+91 98765 43211",
        email: "priya@freshmart.com",
        deliveryRadius: 8,
        avgRating: 4.5,
    },
    {
        id: "PTR-003",
        name: "HealthPlus Pharmacy",
        partnerId: "HPP-2024-003",
        type: "pharmacy",
        location: "Indirapuram, Ghaziabad",
        city: "Ghaziabad",
        status: "active",
        performanceScore: 96,
        totalRevenue: 1250000,
        monthlyRevenue: 125000,
        joinDate: "2023-01-10",
        contactPerson: "Dr. Amit Verma",
        phone: "+91 98765 43212",
        email: "amit@healthplus.com",
        deliveryRadius: 6,
        avgRating: 4.9,
    },
    {
        id: "PTR-004",
        name: "Fashion Hub",
        partnerId: "FH-2024-004",
        type: "retail",
        location: "Saket, Delhi",
        city: "Delhi",
        status: "pending",
        performanceScore: 0,
        totalRevenue: 0,
        monthlyRevenue: 0,
        joinDate: "2024-12-20",
        contactPerson: "Neha Gupta",
        phone: "+91 98765 43213",
        email: "neha@fashionhub.com",
        deliveryRadius: 10,
        avgRating: 0,
    },
    {
        id: "PTR-005",
        name: "Burger King Express",
        partnerId: "BKE-2024-005",
        type: "restaurant",
        location: "Cyber City, Gurugram",
        city: "Gurugram",
        status: "active",
        performanceScore: 92,
        totalRevenue: 3200000,
        monthlyRevenue: 320000,
        joinDate: "2022-11-05",
        contactPerson: "Vikram Singh",
        phone: "+91 98765 43214",
        email: "vikram@burgerking.com",
        deliveryRadius: 7,
        avgRating: 4.6,
    },
    {
        id: "PTR-006",
        name: "Daily Needs Store",
        partnerId: "DNS-2024-006",
        type: "grocery",
        location: "Dwarka, Delhi",
        city: "Delhi",
        status: "inactive",
        performanceScore: 65,
        totalRevenue: 850000,
        monthlyRevenue: 0,
        joinDate: "2023-08-12",
        contactPerson: "Suresh Patel",
        phone: "+91 98765 43215",
        email: "suresh@dailyneeds.com",
        deliveryRadius: 5,
        avgRating: 3.8,
    },
    {
        id: "PTR-007",
        name: "MediCare Plus",
        partnerId: "MCP-2024-007",
        type: "pharmacy",
        location: "Vaishali, Ghaziabad",
        city: "Ghaziabad",
        status: "active",
        performanceScore: 91,
        totalRevenue: 1450000,
        monthlyRevenue: 145000,
        joinDate: "2023-04-18",
        contactPerson: "Dr. Sneha Desai",
        phone: "+91 98765 43216",
        email: "sneha@medicare.com",
        deliveryRadius: 6,
        avgRating: 4.7,
    },
    {
        id: "PTR-008",
        name: "Pizza Paradise",
        partnerId: "PP-2024-008",
        type: "restaurant",
        location: "Greater Kailash, Delhi",
        city: "Delhi",
        status: "active",
        performanceScore: 89,
        totalRevenue: 2100000,
        monthlyRevenue: 210000,
        joinDate: "2023-07-22",
        contactPerson: "Rahul Mehta",
        phone: "+91 98765 43217",
        email: "rahul@pizzaparadise.com",
        deliveryRadius: 8,
        avgRating: 4.4,
    },
];
