
import { Pincode } from "./types";

export const mockPincodes: Pincode[] = [
  {
    id: "1",
    pincode: "400069",
    city: "Mumbai",
    state: "Maharashtra",
    zone: "MUMBAI",
    district: "Mumbai Suburban",
    country: "India",
    isODA: false,
    embargoTags: [],
    stateFormRequired: false,
    serviceability: "express",
    deliveryTime: "1-2 days",
    tatMinDays: 1,
    tatMaxDays: 2,
    cutoffTime: "16:00",
    codAvailable: true,
    prepaidOnly: false,
    maxCodAmount: 50000,
    pickupAvailable: true,
    reversePickupAvailable: true,
    controllingBranchId: "BR-MUM-01",
    serviceCategory: "SELF",
    lastMilePartner: "In-House Fleet",
    hubAssigned: "MUM-CENTRAL",
    status: "active",
    specialInstructions: "High density area, multiple delivery attempts required",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-11T08:30:00Z",
  },
  {
    id: "2",
    pincode: "110019",
    city: "Delhi",
    state: "Delhi",
    zone: "DELHI",
    district: "South Delhi",
    country: "India",
    isODA: false,
    embargoTags: ["LIQUIDS"],
    stateFormRequired: false,
    serviceability: "same_day",
    deliveryTime: "Same Day",
    tatMinDays: 0,
    tatMaxDays: 0,
    cutoffTime: "11:00",
    codAvailable: true,
    prepaidOnly: false,
    pickupAvailable: true,
    reversePickupAvailable: true,
    controllingBranchId: "BR-DEL-02",
    serviceCategory: "SELF",
    lastMilePartner: "In-House Fleet",
    hubAssigned: "DEL-NORTH",
    status: "active",
    specialInstructions: "Commercial area, delivery before 6 PM",
    createdAt: "2024-02-20T14:30:00Z",
    updatedAt: "2024-12-11T09:15:00Z",
  },
  {
    id: "3",
    pincode: "560034",
    city: "Bangalore",
    state: "Karnataka",
    zone: "BANGALORE",
    district: "Bangalore Urban",
    country: "India",
    isODA: true,
    odaType: "REGULAR",
    embargoTags: [],
    stateFormRequired: false,
    serviceability: "next_day",
    deliveryTime: "Next Day",
    tatMinDays: 1,
    tatMaxDays: 1,
    cutoffTime: "14:00",
    codAvailable: true,
    prepaidOnly: false,
    maxCodAmount: 20000,
    pickupAvailable: false,
    reversePickupAvailable: false,
    controllingBranchId: "BR-BLR-03",
    serviceCategory: "PARTNER",
    lastMilePartner: "Bangalore Express",
    hubAssigned: "BLR-SOUTH",
    status: "active",
    specialInstructions: "IT corridor, prefer evening deliveries",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-12-10T16:45:00Z",
  },
  {
    id: "4",
    pincode: "793001",
    city: "Shillong",
    state: "Meghalaya",
    zone: "NORTH_EAST",
    district: "East Khasi Hills",
    country: "India",
    isODA: true,
    odaType: "SPECIAL",
    embargoTags: ["HEAVY_MACHINERY", "LIQUIDS"],
    stateFormRequired: true,
    serviceability: "standard",
    deliveryTime: "5-7 days",
    tatMinDays: 5,
    tatMaxDays: 7,
    codAvailable: false,
    prepaidOnly: true,
    pickupAvailable: false,
    reversePickupAvailable: false,
    controllingBranchId: "BR-NE-EXT",
    serviceCategory: "FRANCHISE",
    lastMilePartner: "Hill Transporters",
    hubAssigned: "GHY-HUB",
    status: "active",
    specialInstructions: "Hill station, weather dependent delivery time.",
    createdAt: "2024-04-05T11:00:00Z",
    updatedAt: "2024-12-11T10:20:00Z",
  },
  {
    id: "5",
    pincode: "500034",
    city: "Hyderabad",
    state: "Telangana",
    zone: "HYDERABAD",
    district: "Hyderabad",
    country: "India",
    isODA: false,
    embargoTags: [],
    stateFormRequired: false,
    serviceability: "express",
    deliveryTime: "1-2 days",
    tatMinDays: 1,
    tatMaxDays: 2,
    cutoffTime: "15:00",
    codAvailable: true,
    prepaidOnly: false,
    pickupAvailable: true,
    reversePickupAvailable: true,
    controllingBranchId: "BR-HYD-04",
    serviceCategory: "SELF",
    lastMilePartner: "In-House Fleet",
    hubAssigned: "HYD-OFFICE",
    status: "active",
    specialInstructions: "Tech park area, security clearance required",
    createdAt: "2024-05-15T13:00:00Z",
    updatedAt: "2024-12-11T11:30:00Z",
  }
];
