// components/master/pincodes/mockData.ts
import { Pincode } from "./types";

export const mockPincodes: Pincode[] = [
  {
    id: "1",
    pincode: "400069",
    city: "Mumbai",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    country: "India",
    serviceability: "express",
    deliveryTime: "1-2 days",
    codAvailable: true,
    pickupAvailable: true,
    lastMilePartner: "QuickDel Logistics",
    hubAssigned: "MUM-CENTRAL",
    status: "active",
    specialInstructions:
      "High density area, multiple delivery attempts required",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-11T08:30:00Z",
  },
  {
    id: "2",
    pincode: "110019",
    city: "Delhi",
    state: "Delhi",
    district: "South Delhi",
    country: "India",
    serviceability: "same_day",
    deliveryTime: "Same day",
    codAvailable: true,
    pickupAvailable: true,
    lastMilePartner: "Metro Couriers",
    hubAssigned: "DEL-NORTH",
    status: "active",
    specialInstructions: "Commercial area, delivery before 6 PM",
    createdAt: "2024-02-20T14:30:00Z",
    updatedAt: "2024-12-11T09:15:00Z",
  },
  {
    id: "3",
    pincode: "560034",
    city: "Bangalore",
    state: "Karnataka",
    district: "Bangalore Urban",
    country: "India",
    serviceability: "next_day",
    deliveryTime: "Next day",
    codAvailable: true,
    pickupAvailable: false,
    lastMilePartner: "Bangalore Express",
    hubAssigned: "BLR-SOUTH",
    status: "active",
    specialInstructions: "IT corridor, prefer evening deliveries",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-12-10T16:45:00Z",
  },
  {
    id: "4",
    pincode: "600032",
    city: "Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    country: "India",
    serviceability: "standard",
    deliveryTime: "3-4 days",
    codAvailable: false,
    pickupAvailable: true,
    lastMilePartner: "Chennai Logistics",
    hubAssigned: "CHE-PROC",
    status: "active",
    specialInstructions: "Industrial area, limited access during peak hours",
    createdAt: "2024-04-05T11:00:00Z",
    updatedAt: "2024-12-11T10:20:00Z",
  },
  {
    id: "5",
    pincode: "500034",
    city: "Hyderabad",
    state: "Telangana",
    district: "Hyderabad",
    country: "India",
    serviceability: "express",
    deliveryTime: "1-2 days",
    codAvailable: true,
    pickupAvailable: true,
    lastMilePartner: "Hyderabad Couriers",
    hubAssigned: "HYD-OFFICE",
    status: "active",
    specialInstructions: "Tech park area, security clearance required",
    createdAt: "2024-05-15T13:00:00Z",
    updatedAt: "2024-12-11T11:30:00Z",
  },
  {
    id: "6",
    pincode: "700091",
    city: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    country: "India",
    serviceability: "non_serviceable",
    deliveryTime: "N/A",
    codAvailable: false,
    pickupAvailable: false,
    lastMilePartner: "N/A",
    hubAssigned: "N/A",
    status: "inactive",
    specialInstructions: "Remote area, no service coverage",
    createdAt: "2024-06-20T15:00:00Z",
    updatedAt: "2024-12-10T14:15:00Z",
  },
  {
    id: "7",
    pincode: "380009",
    city: "Ahmedabad",
    state: "Gujarat",
    district: "Ahmedabad",
    country: "India",
    serviceability: "standard",
    deliveryTime: "2-3 days",
    codAvailable: true,
    pickupAvailable: true,
    lastMilePartner: "Gujarat Express",
    hubAssigned: "AHD-CENTRAL",
    status: "active",
    specialInstructions: "Commercial area, early morning deliveries preferred",
    createdAt: "2024-07-12T08:00:00Z",
    updatedAt: "2024-12-11T12:00:00Z",
  },
  {
    id: "8",
    pincode: "411001",
    city: "Pune",
    state: "Maharashtra",
    district: "Pune",
    country: "India",
    serviceability: "same_day",
    deliveryTime: "Same day",
    codAvailable: true,
    pickupAvailable: true,
    lastMilePartner: "Pune Quick Delivery",
    hubAssigned: "PUN-CENTRAL",
    status: "active",
    specialInstructions: "IT park, delivery between 10 AM - 6 PM",
    createdAt: "2024-08-08T10:30:00Z",
    updatedAt: "2024-12-11T13:45:00Z",
  },
  {
    id: "9",
    pincode: "302001",
    city: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    country: "India",
    serviceability: "next_day",
    deliveryTime: "Next day",
    codAvailable: true,
    pickupAvailable: false,
    lastMilePartner: "Rajasthan Couriers",
    hubAssigned: "JPR-WEST",
    status: "active",
    specialInstructions: "Heritage area, vehicle restrictions apply",
    createdAt: "2024-09-25T14:00:00Z",
    updatedAt: "2024-12-11T14:20:00Z",
  },
  {
    id: "10",
    pincode: "452001",
    city: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    country: "India",
    serviceability: "standard",
    deliveryTime: "3-4 days",
    codAvailable: false,
    pickupAvailable: true,
    lastMilePartner: "MP Logistics",
    hubAssigned: "IND-CENTRAL",
    status: "inactive",
    specialInstructions:
      "Service temporarily suspended due to logistics issues",
    createdAt: "2024-10-30T16:00:00Z",
    updatedAt: "2024-12-10T17:30:00Z",
  },
];
