import { Asset, AssetStat } from "./types";
import { Box, Activity, Wrench, TrendingDown } from "lucide-react";

export const assetStats: AssetStat[] = [
    {
        title: "Total Assets",
        value: "342",
        change: "+8",
        trend: "up",
        icon: Box,
        description: "Tracked items",
    },
    {
        title: "Active Assets",
        value: "298",
        change: "+5",
        trend: "up",
        icon: Activity,
        description: "In operation",
    },
    {
        title: "Under Maintenance",
        value: "12",
        change: "+3",
        trend: "down",
        icon: Wrench,
        description: "Being serviced",
    },
    {
        title: "Depreciation Value",
        value: "₹12.5L",
        change: "-2.3%",
        trend: "down",
        icon: TrendingDown,
        description: "This quarter",
    },
];

export const assetData: Asset[] = [
    {
        id: "AST-001",
        name: "Forklift - Toyota 8FD25",
        assetId: "FLT-2024-001",
        category: "Material Handling",
        location: "Warehouse A - Loading Bay",
        condition: "excellent",
        purchaseDate: "2023-06-15",
        purchaseValue: 850000,
        currentValue: 765000,
        status: "active",
        assignedTo: "Rajesh Kumar",
        lastMaintenance: "2024-12-10",
        nextMaintenance: "2025-03-10",
    },
    {
        id: "AST-002",
        name: "Pallet Jack - Electric",
        assetId: "PLJ-2024-002",
        category: "Material Handling",
        location: "Warehouse B - Storage Area",
        condition: "good",
        purchaseDate: "2023-08-20",
        purchaseValue: 125000,
        currentValue: 106250,
        status: "active",
        assignedTo: "Amit Sharma",
        lastMaintenance: "2024-11-25",
        nextMaintenance: "2025-02-25",
    },
    {
        id: "AST-003",
        name: "Conveyor Belt System",
        assetId: "CVB-2024-003",
        category: "Automation",
        location: "Warehouse A - Sorting Area",
        condition: "fair",
        purchaseDate: "2022-03-10",
        purchaseValue: 1500000,
        currentValue: 1050000,
        status: "maintenance",
        assignedTo: "Maintenance Team",
        lastMaintenance: "2024-12-20",
        nextMaintenance: "2025-01-05",
    },
    {
        id: "AST-004",
        name: "Barcode Scanner - Handheld",
        assetId: "BCS-2024-004",
        category: "Technology",
        location: "Warehouse C - Receiving",
        condition: "excellent",
        purchaseDate: "2024-01-15",
        purchaseValue: 45000,
        currentValue: 42750,
        status: "active",
        assignedTo: "Priya Patel",
        lastMaintenance: "2024-12-01",
        nextMaintenance: "2025-06-01",
    },
    {
        id: "AST-005",
        name: "Industrial Shelving Unit",
        assetId: "SHL-2024-005",
        category: "Storage",
        location: "Warehouse B - Aisle 5",
        condition: "good",
        purchaseDate: "2022-11-05",
        purchaseValue: 185000,
        currentValue: 129500,
        status: "active",
        assignedTo: "Warehouse B Team",
        lastMaintenance: "2024-09-15",
        nextMaintenance: "2025-03-15",
    },
    {
        id: "AST-006",
        name: "Reach Truck",
        assetId: "RCT-2024-006",
        category: "Material Handling",
        location: "Warehouse A - High Bay",
        condition: "good",
        purchaseDate: "2023-04-20",
        purchaseValue: 950000,
        currentValue: 808000,
        status: "active",
        assignedTo: "Vikram Singh",
        lastMaintenance: "2024-12-05",
        nextMaintenance: "2025-03-05",
    },
    {
        id: "AST-007",
        name: "Loading Dock Leveler",
        assetId: "LDL-2024-007",
        category: "Infrastructure",
        location: "Warehouse A - Dock 3",
        condition: "poor",
        purchaseDate: "2020-07-10",
        purchaseValue: 350000,
        currentValue: 140000,
        status: "maintenance",
        assignedTo: "Maintenance Team",
        lastMaintenance: "2024-12-18",
        nextMaintenance: "2025-01-02",
    },
    {
        id: "AST-008",
        name: "CCTV Camera System",
        assetId: "CCT-2024-008",
        category: "Security",
        location: "All Warehouses",
        condition: "excellent",
        purchaseDate: "2023-09-01",
        purchaseValue: 425000,
        currentValue: 361250,
        status: "active",
        assignedTo: "Security Team",
        lastMaintenance: "2024-11-30",
        nextMaintenance: "2025-05-30",
    },
];
