// components/master/customers/mockData.ts
import { Customer } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "1",
    code: "YELLOWRAJAST",
    name: "YELLOW THREAD INDIA PRIVATE LIMITED",
    contactPerson: "Rajesh Kumar",
    address1: "PLOT NO 29, MIG PHASE 1",
    address2: "VANASTHALIPURAM",
    city: "JAIPUR",
    station: "RANGA REDDY",
    pincode: "500070",
    gstin: "36AAACY4430D1ZN",
    mobileNo: "9876543210",
    phoneO: "0141-1234567",
    phoneR: "0141-1234568",
    email: "info@yellowthread.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-1",
        name: "Amit Sharma",
        address: "Shop No 45, Market Complex",
        city: "Mumbai",
        pincode: "400001",
        mobileNo: "9876543211",
        email: "amit@yellowthread.com",
      },
      {
        id: "rec-2",
        name: "Priya Singh",
        address: "Office No 12, Business Park",
        city: "Delhi",
        pincode: "110001",
        mobileNo: "9876543212",
        email: "priya@yellowthread.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-1",
        name: "Main Warehouse",
        address: "Warehouse No 5, Industrial Area",
        city: "Jaipur",
        pincode: "302022",
        contactPerson: "Ramesh Kumar",
        mobileNo: "9876543213",
      },
    ],
    status: "active",
    fuelCharges: 0.0,
    fovCharges: 0.0,
    quotationType: "Standard",
    awt: 0.0,
    category: "CUSTOMER",
    paymentMode: "Credit",
    accountGroup: "Corporate",
    isInterStateDealer: true,
    documentNo: "DOC12345",
    bookedBy: "ADMIN",
    bookedDate: "18/11/2024 5:10:12",
    remark: "Premium customer with regular shipments",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-11T08:30:00Z",
  },
  {
    id: "2",
    code: "GREENFIB",
    name: "GREEN FIBERS CORPORATION",
    contactPerson: "Amit Patel",
    address1: "BLOCK B, SECTOR 25",
    address2: "MALVIYA NAGAR",
    city: "DELHI",
    station: "DELHI",
    pincode: "110017",
    gstin: "07AABCU9603R1ZN",
    mobileNo: "9876543212",
    phoneO: "011-3456789",
    phoneR: "011-3456790",
    email: "operations@greenfib.com",
    hasReceiver: true,
    receivers: [
      {
        id: "rec-3",
        name: "Sanjay Verma",
        address: "Godown No 8, Transport Nagar",
        city: "Gurgaon",
        pincode: "122001",
        mobileNo: "9876543214",
        email: "sanjay@greenfib.com",
      },
    ],
    usePickupLocation: true,
    pickupLocations: [
      {
        id: "pickup-2",
        name: "Factory Unit",
        address: "Unit 15, SEZ Area",
        city: "Delhi",
        pincode: "110020",
        contactPerson: "Vikram Singh",
        mobileNo: "9876543215",
      },
      {
        id: "pickup-3",
        name: "Distribution Center",
        address: "Sector 18, Industrial Estate",
        city: "Noida",
        pincode: "201301",
        contactPerson: "Neha Gupta",
        mobileNo: "9876543216",
      },
    ],
    status: "inactive",
    fuelCharges: 1.5,
    fovCharges: 0.75,
    quotationType: "Economy",
    awt: 0.25,
    category: "CUSTOMER",
    paymentMode: "Credit",
    accountGroup: "Enterprise",
    isInterStateDealer: true,
    documentNo: "DOC12347",
    bookedBy: "ADMIN",
    bookedDate: "17/11/2024 3:20:00",
    remark: "Temporarily suspended account",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-12-10T16:45:00Z",
  },
];
