import { AttendanceRecord } from "./types";

export const mockAttendance: AttendanceRecord[] = [
    {
        id: "ATT-001",
        name: "Vikram Singh",
        riderId: "RS-1001",
        date: "2024-12-24",
        checkIn: "08:00 AM",
        checkOut: "05:00 PM",
        status: "present",
        shift: "morning",
        totalHours: "9h 0m",
    },
    {
        id: "ATT-002",
        name: "Amit Kumar",
        riderId: "RS-1002",
        date: "2024-12-24",
        checkIn: "08:15 AM",
        checkOut: "05:15 PM",
        status: "late",
        shift: "morning",
        totalHours: "9h 0m",
    },
    {
        id: "ATT-003",
        name: "Rahul Sharma",
        riderId: "RS-1003",
        date: "2024-12-24",
        checkIn: "-",
        checkOut: "-",
        status: "absent",
        shift: "morning",
        totalHours: "0h",
    },
    {
        id: "ATT-004",
        name: "Suresh Patel",
        riderId: "RS-1004",
        date: "2024-12-24",
        checkIn: "02:00 PM",
        checkOut: "10:00 PM",
        status: "present",
        shift: "evening",
        totalHours: "8h 0m",
    },
    {
        id: "ATT-005",
        name: "Deepak Verma",
        riderId: "RS-1005",
        date: "2024-12-24",
        checkIn: "10:00 AM",
        checkOut: "02:00 PM",
        status: "half-day",
        shift: "morning",
        totalHours: "4h 0m",
    },
];
