import { Rider } from "./types";

export const mockRiders: Rider[] = [
    {
        id: "R-001",
        name: "Vikram Singh",
        riderId: "RS-1001",
        phone: "+91 98765 43210",
        zone: "North Delhi",
        status: "active",
        vehicleType: "bike",
        currentLoad: 80,
        assignedOrders: 12,
        shift: "morning",
        joiningDate: "2024-01-15",
        rating: 4.8,
    },
    {
        id: "R-002",
        name: "Amit Kumar",
        riderId: "RS-1002",
        phone: "+91 98765 12345",
        zone: "South Delhi",
        status: "active",
        vehicleType: "scooter",
        currentLoad: 45,
        assignedOrders: 5,
        shift: "evening",
        joiningDate: "2024-02-10",
        rating: 4.5,
    },
    {
        id: "R-003",
        name: "Rahul Sharma",
        riderId: "RS-1003",
        phone: "+91 98765 67890",
        zone: "West Delhi",
        status: "on-leave",
        vehicleType: "ev",
        currentLoad: 0,
        assignedOrders: 0,
        shift: "full-day",
        joiningDate: "2023-11-05",
        rating: 4.9,
    },
    {
        id: "R-004",
        name: "Suresh Patel",
        riderId: "RS-1004",
        phone: "+91 98765 54321",
        zone: "East Delhi",
        status: "inactive",
        vehicleType: "bike",
        currentLoad: 0,
        assignedOrders: 0,
        shift: "night",
        joiningDate: "2024-03-01",
        rating: 4.2,
    },
    {
        id: "R-005",
        name: "Deepak Verma",
        riderId: "RS-1005",
        phone: "+91 98765 98765",
        zone: "Central Delhi",
        status: "active",
        vehicleType: "ev",
        currentLoad: 90,
        assignedOrders: 15,
        shift: "morning",
        joiningDate: "2024-01-20",
        rating: 4.7,
    },
];
