// components/master/rates/mockData.ts
import { RateRule } from "./types";

export const mockRateRules: RateRule[] = [
  {
    id: "RATE-001",
    name: "Standard Corporate Rates",
    customerType: "CUSTOMER",
    serviceType: "SURFACE",
    paymentMode: "ALL",
    slabs: [
      {
        id: "1",
        slabName: "0-1 kg",
        minWeight: 0,
        maxWeight: 1,
        rate: 50,
        rateType: "FIXED",
      },
      {
        id: "2",
        slabName: "1-5 kg",
        minWeight: 1,
        maxWeight: 5,
        rate: 20,
        rateType: "PER_KG",
      },
      {
        id: "3",
        slabName: "5-10 kg",
        minWeight: 5,
        maxWeight: 10,
        rate: 18,
        rateType: "PER_KG",
      },
      {
        id: "4",
        slabName: "10-20 kg",
        minWeight: 10,
        maxWeight: 20,
        rate: 15,
        rateType: "PER_KG",
      },
    ],
    zones: [
      {
        id: "1",
        fromZone: "DELHI",
        toZone: "MUMBAI",
        rate: 120,
        transitDays: 3,
        isActive: true,
      },
      {
        id: "2",
        fromZone: "DELHI",
        toZone: "BANGALORE",
        rate: 150,
        transitDays: 4,
        isActive: true,
      },
      {
        id: "3",
        fromZone: "DELHI",
        toZone: "CHENNAI",
        rate: 180,
        transitDays: 5,
        isActive: true,
      },
    ],
    fuelSurcharge: {
      percentage: 5,
      minAmount: 10,
      maxAmount: 100,
      applicableFrom: 0,
    },
    fovCharge: { percentage: 2, minAmount: 20, maxAmount: 500 },
    codCharges: { percentage: 10, minAmount: 15, fixedCharge: 20 },
    minCharge: { amount: 30, applicableZones: ["ALL"] },
    additionalCharges: [
      {
        id: "1",
        name: "ODA Charge",
        type: "FIXED",
        value: 50,
        description: "Out of Delivery Area",
      },
      {
        id: "2",
        name: "Sunday/Holiday",
        type: "PERCENTAGE",
        value: 25,
        description: "Delivery on Sunday/Holiday",
      },
      {
        id: "3",
        name: "Special Handling",
        type: "FIXED",
        value: 100,
        description: "Fragile/Perishable items",
      },
    ],
    validFrom: "2024-01-01",
    validTo: "2025-12-31",
    isActive: true,
    autoCalculate: {
      enabled: true,
      baseOn: "BOTH",
      rounding: "UP",
      roundingFactor: 0.5,
    },
    restrictions: {
      maxWeight: 50,
      minWeight: 0.1,
      allowedPackaging: ["BOX", "ENVELOPE", "BAG"],
      prohibitedItems: ["LIQUIDS", "EXPLOSIVES", "WEAPONS"],
      specialInstructions: "Handle with care",
    },
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-01-01T10:00:00Z",
    createdBy: "Admin",
  },
  {
    id: "RATE-002",
    name: "Express Air Freight",
    customerType: "AGENT",
    serviceType: "AIR",
    paymentMode: "PREPAID",
    slabs: [
      {
        id: "1",
        slabName: "0-0.5 kg",
        minWeight: 0,
        maxWeight: 0.5,
        rate: 100,
        rateType: "FIXED",
      },
      {
        id: "2",
        slabName: "0.5-5 kg",
        minWeight: 0.5,
        maxWeight: 5,
        rate: 40,
        rateType: "PER_KG",
      },
    ],
    zones: [
      {
        id: "1",
        fromZone: "DELHI",
        toZone: "MUMBAI",
        rate: 200,
        transitDays: 1,
        isActive: true,
      },
      {
        id: "2",
        fromZone: "DELHI",
        toZone: "BANGALORE",
        rate: 250,
        transitDays: 1,
        isActive: true,
      },
    ],
    fuelSurcharge: {
      percentage: 8,
      minAmount: 15,
      maxAmount: 150,
      applicableFrom: 0,
    },
    fovCharge: { percentage: 2.5, minAmount: 25, maxAmount: 1000 },
    codCharges: { percentage: 12, minAmount: 20, fixedCharge: 25 },
    minCharge: { amount: 50, applicableZones: ["ALL"] },
    additionalCharges: [
      {
        id: "1",
        name: "Priority Handling",
        type: "FIXED",
        value: 75,
        description: "Priority booking and handling",
      },
    ],
    validFrom: "2024-01-01",
    validTo: "2025-12-30",
    isActive: true,
    autoCalculate: {
      enabled: true,
      baseOn: "BOTH",
      rounding: "UP",
      roundingFactor: 0.5,
    },
    restrictions: {
      maxWeight: 25,
      minWeight: 0.1,
      allowedPackaging: ["BOX", "ENVELOPE"],
      prohibitedItems: ["LIQUIDS", "HAZARDOUS"],
      specialInstructions: "Priority handling required",
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    createdBy: "Admin",
  },
  {
    id: "RATE-003",
    name: "Vendor Special Rates",
    customerType: "VENDOR",
    serviceType: "ALL",
    paymentMode: "CREDIT",
    slabs: [
      {
        id: "1",
        slabName: "0-10 kg",
        minWeight: 0,
        maxWeight: 10,
        rate: 12,
        rateType: "PER_KG",
      },
      {
        id: "2",
        slabName: "10-50 kg",
        minWeight: 10,
        maxWeight: 50,
        rate: 10,
        rateType: "PER_KG",
      },
    ],
    zones: [
      {
        id: "1",
        fromZone: "DELHI",
        toZone: "MUMBAI",
        rate: 15,
        transitDays: 4,
        isActive: true,
      },
      {
        id: "2",
        fromZone: "DELHI",
        toZone: "BANGALORE",
        rate: 18,
        transitDays: 5,
        isActive: true,
      },
    ],
    fuelSurcharge: {
      percentage: 4,
      minAmount: 8,
      maxAmount: 80,
      applicableFrom: 0,
    },
    fovCharge: { percentage: 1.5, minAmount: 15, maxAmount: 300 },
    codCharges: { percentage: 8, minAmount: 12, fixedCharge: 15 },
    minCharge: { amount: 25, applicableZones: ["ALL"] },
    additionalCharges: [],
    validFrom: "2024-02-01",
    validTo: "2024-12-31",
    isActive: true,
    autoCalculate: {
      enabled: true,
      baseOn: "BOTH",
      rounding: "DOWN",
      roundingFactor: 1,
    },
    restrictions: {
      maxWeight: 100,
      minWeight: 1,
      allowedPackaging: ["BOX", "PALLET"],
      prohibitedItems: [],
      specialInstructions: "Bulk shipments only",
    },
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-01T10:00:00Z",
    createdBy: "Admin",
  },
  {
    id: "RATE-004",
    name: "Expired Corporate Rates",
    customerType: "CUSTOMER",
    serviceType: "SURFACE",
    paymentMode: "ALL",
    slabs: [
      {
        id: "1",
        slabName: "0-1 kg",
        minWeight: 0,
        maxWeight: 1,
        rate: 45,
        rateType: "FIXED",
      },
      {
        id: "2",
        slabName: "1-5 kg",
        minWeight: 1,
        maxWeight: 5,
        rate: 18,
        rateType: "PER_KG",
      },
    ],
    zones: [
      {
        id: "1",
        fromZone: "DELHI",
        toZone: "MUMBAI",
        rate: 110,
        transitDays: 3,
        isActive: true,
      },
    ],
    fuelSurcharge: {
      percentage: 4,
      minAmount: 8,
      maxAmount: 80,
      applicableFrom: 0,
    },
    fovCharge: { percentage: 1.5, minAmount: 15, maxAmount: 300 },
    codCharges: { percentage: 8, minAmount: 12, fixedCharge: 15 },
    minCharge: { amount: 25, applicableZones: ["ALL"] },
    additionalCharges: [],
    validFrom: "2023-01-01",
    validTo: "2023-12-31",
    isActive: false,
    autoCalculate: {
      enabled: true,
      baseOn: "BOTH",
      rounding: "UP",
      roundingFactor: 0.5,
    },
    restrictions: {
      maxWeight: 50,
      minWeight: 0.1,
      allowedPackaging: ["BOX", "ENVELOPE", "BAG"],
      prohibitedItems: ["LIQUIDS", "EXPLOSIVES", "WEAPONS"],
      specialInstructions: "Handle with care",
    },
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2023-12-31T10:00:00Z",
    createdBy: "Admin",
  },
];

// Additional mock data
export const zonesList = [
  "DELHI",
  "MUMBAI",
  "BANGALORE",
  "CHENNAI",
  "KOLKATA",
  "HYDERABAD",
  "AHMEDABAD",
  "PUNE",
  "JAIPUR",
  "LUCKNOW",
  "CHANDIGARH",
  "KOCHI",
];

export const serviceTypes = ["SURFACE", "AIR", "EXPRESS", "ALL"];
export const customerTypes = ["CUSTOMER", "AGENT", "VENDOR", "ALL"];
export const paymentModes = ["PREPAID", "COD", "CREDIT", "ALL"];
