import { ReconciliationRecord, ReconciliationStat } from "./types";
import { ClipboardList, AlertTriangle, CheckCircle, TrendingUp } from "lucide-react";

export const reconciliationStats: ReconciliationStat[] = [
    {
        title: "Pending Reconciliations",
        value: "15",
        change: "+3",
        trend: "down",
        icon: ClipboardList,
        description: "Awaiting review",
    },
    {
        title: "Discrepancies Found",
        value: "7",
        change: "-2",
        trend: "up",
        icon: AlertTriangle,
        description: "Requires attention",
    },
    {
        title: "Resolved Today",
        value: "12",
        change: "+4",
        trend: "up",
        icon: CheckCircle,
        description: "Completed",
    },
    {
        title: "Accuracy Rate",
        value: "96.8%",
        change: "+1.2%",
        trend: "up",
        icon: TrendingUp,
        description: "This month",
    },
];

export const reconciliationData: ReconciliationRecord[] = [
    {
        id: "REC-001",
        itemName: "Delivery Bags - Large",
        sku: "DB-LRG-001",
        category: "Packaging",
        expectedQty: 450,
        actualQty: 445,
        variance: -5,
        variancePercent: -1.11,
        status: "discrepancy",
        reconciledBy: "Rahul Sharma",
        reconciledDate: "2024-12-23",
        location: "Warehouse A - Shelf 12",
        notes: "Minor discrepancy, investigating",
    },
    {
        id: "REC-002",
        itemName: "Thermal Labels (Roll)",
        sku: "TL-100-002",
        category: "Supplies",
        expectedQty: 85,
        actualQty: 85,
        variance: 0,
        variancePercent: 0,
        status: "resolved",
        reconciledBy: "Priya Patel",
        reconciledDate: "2024-12-23",
        location: "Warehouse A - Shelf 5",
        notes: "Stock count verified",
    },
    {
        id: "REC-003",
        itemName: "Handheld Scanners",
        sku: "HS-PRO-003",
        category: "Equipment",
        expectedQty: 12,
        actualQty: 10,
        variance: -2,
        variancePercent: -16.67,
        status: "in-progress",
        reconciledBy: "Amit Kumar",
        reconciledDate: "2024-12-23",
        location: "Warehouse B - Equipment Room",
        notes: "2 units out for repair",
    },
    {
        id: "REC-004",
        itemName: "Packing Tape - Heavy Duty",
        sku: "PT-HD-004",
        category: "Packaging",
        expectedQty: 320,
        actualQty: 320,
        variance: 0,
        variancePercent: 0,
        status: "resolved",
        reconciledBy: "Sneha Desai",
        reconciledDate: "2024-12-22",
        location: "Warehouse A - Shelf 8",
        notes: "Count accurate",
    },
    {
        id: "REC-005",
        itemName: "Safety Vests",
        sku: "SV-STD-005",
        category: "Safety",
        expectedQty: 50,
        actualQty: 42,
        variance: -8,
        variancePercent: -16.0,
        status: "discrepancy",
        reconciledBy: "Vikram Singh",
        reconciledDate: "2024-12-23",
        location: "Warehouse C - Safety Storage",
        notes: "Significant variance, audit required",
    },
    {
        id: "REC-006",
        itemName: "Delivery Boxes - Medium",
        sku: "DB-MED-006",
        category: "Packaging",
        expectedQty: 680,
        actualQty: 680,
        variance: 0,
        variancePercent: 0,
        status: "resolved",
        reconciledBy: "Neha Gupta",
        reconciledDate: "2024-12-22",
        location: "Warehouse A - Shelf 15",
        notes: "Verified and accurate",
    },
    {
        id: "REC-007",
        itemName: "Bubble Wrap (Roll)",
        sku: "BW-50M-007",
        category: "Packaging",
        expectedQty: 125,
        actualQty: 128,
        variance: 3,
        variancePercent: 2.4,
        status: "pending",
        reconciledBy: "Unassigned",
        reconciledDate: "2024-12-23",
        location: "Warehouse A - Shelf 10",
        notes: "Awaiting reconciliation",
    },
    {
        id: "REC-008",
        itemName: "First Aid Kits",
        sku: "FAK-PRO-010",
        category: "Safety",
        expectedQty: 25,
        actualQty: 18,
        variance: -7,
        variancePercent: -28.0,
        status: "in-progress",
        reconciledBy: "Rajesh Mehta",
        reconciledDate: "2024-12-23",
        location: "Warehouse C - Safety Storage",
        notes: "Investigating large variance",
    },
];
