import { BranchPerformance, PerformanceStat } from "./types";
import { TrendingUp, TrendingDown, Minus, Trophy, Target, AlertTriangle, Clock } from "lucide-react";

export const performanceStats: PerformanceStat[] = [
    {
        title: "Avg. Performance",
        value: "87%",
        change: "+2.4%",
        trend: "up",
        icon: TrendingUp,
        description: "vs. last month",
    },
    {
        title: "Top Performer",
        value: "Mumbai Central",
        change: "98%",
        trend: "neutral",
        icon: Trophy,
        description: "Score this month",
    },
    {
        title: "SLA Compliance",
        value: "94.2%",
        change: "-0.5%",
        trend: "down",
        icon: Target,
        description: "Delivery time targets",
    },
    {
        title: "Active Issues",
        value: "12",
        change: "-3",
        trend: "up",
        icon: AlertTriangle,
        description: "Requires attention",
    },
];

export const performanceData: BranchPerformance[] = [
    {
        id: "BP-001",
        name: "Mumbai Central Hub",
        code: "MUM-CENT",
        type: "company",
        manager: "Rajesh Kumar",
        location: "Mumbai, MH",
        performanceScore: 98,
        deliverySuccessRate: 99.2,
        customerSatisfaction: 4.8,
        avgDeliveryTime: "42m",
        activeIssues: 0,
        revenue: 4.2,
        status: "active",
        lastAuditDate: "2024-12-15",
        trend: "up",
    },
    {
        id: "BP-002",
        name: "Delhi North Gateway",
        code: "DEL-NORTH",
        type: "company",
        manager: "Priya Singh",
        location: "Delhi, DL",
        performanceScore: 92,
        deliverySuccessRate: 97.5,
        customerSatisfaction: 4.6,
        avgDeliveryTime: "45m",
        activeIssues: 1,
        revenue: 3.8,
        status: "active",
        lastAuditDate: "2024-12-10",
        trend: "stable",
    },
    {
        id: "BP-003",
        name: "Bangalore Tech Park",
        code: "BLR-TECH",
        type: "company",
        manager: "Arun Mehta",
        location: "Bangalore, KA",
        performanceScore: 88,
        deliverySuccessRate: 96.0,
        customerSatisfaction: 4.5,
        avgDeliveryTime: "50m",
        activeIssues: 2,
        revenue: 3.5,
        status: "warning",
        lastAuditDate: "2024-12-12",
        trend: "down",
    },
    {
        id: "BP-004",
        name: "Chennai Coastal Hub",
        code: "CHE-COAST",
        type: "partner",
        manager: "Suresh Raman",
        location: "Chennai, TN",
        performanceScore: 85,
        deliverySuccessRate: 94.8,
        customerSatisfaction: 4.3,
        avgDeliveryTime: "55m",
        activeIssues: 4,
        revenue: 2.8,
        status: "warning",
        lastAuditDate: "2024-12-18",
        trend: "stable",
    },
    {
        id: "BP-005",
        name: "Hyderabad Tech City",
        code: "HYD-TECH",
        type: "company",
        manager: "Anjali Reddy",
        location: "Hyderabad, TG",
        performanceScore: 95,
        deliverySuccessRate: 98.4,
        customerSatisfaction: 4.7,
        avgDeliveryTime: "38m",
        activeIssues: 0,
        revenue: 3.2,
        status: "active",
        lastAuditDate: "2024-12-20",
        trend: "up",
    },
    {
        id: "BP-006",
        name: "Kolkata Eastern Hub",
        code: "KOL-EAST",
        type: "partner",
        manager: "Amit Banerjee",
        location: "Kolkata, WB",
        performanceScore: 72,
        deliverySuccessRate: 88.5,
        customerSatisfaction: 3.9,
        avgDeliveryTime: "65m",
        activeIssues: 8,
        revenue: 2.1,
        status: "critical",
        lastAuditDate: "2024-12-05",
        trend: "down",
    },
    {
        id: "BP-007",
        name: "Pune IT Park",
        code: "PUN-IT",
        type: "company",
        manager: "Neha Sharma",
        location: "Pune, MH",
        performanceScore: 90,
        deliverySuccessRate: 97.1,
        customerSatisfaction: 4.5,
        avgDeliveryTime: "48m",
        activeIssues: 1,
        revenue: 2.9,
        status: "active",
        lastAuditDate: "2024-12-14",
        trend: "stable",
    },
    {
        id: "BP-008",
        name: "Ahmedabad Central",
        code: "AHM-CENT",
        type: "partner",
        manager: "Vikram Patel",
        location: "Ahmedabad, GJ",
        performanceScore: 78,
        deliverySuccessRate: 91.2,
        customerSatisfaction: 4.1,
        avgDeliveryTime: "52m",
        activeIssues: 5,
        revenue: 1.4,
        status: "warning",
        lastAuditDate: "2024-12-08",
        trend: "down",
    },
];
