import { OnboardingApplication, OnboardingStat } from "./types";
import { FileText, Clock, CheckCircle, TrendingUp } from "lucide-react";

export const onboardingStats: OnboardingStat[] = [
    {
        title: "Pending Applications",
        value: "18",
        change: "+6",
        trend: "down",
        icon: FileText,
        description: "Awaiting review",
    },
    {
        title: "In Review",
        value: "12",
        change: "+3",
        trend: "neutral",
        icon: Clock,
        description: "Being processed",
    },
    {
        title: "Approved Today",
        value: "5",
        change: "+2",
        trend: "up",
        icon: CheckCircle,
        description: "Ready to onboard",
    },
    {
        title: "Avg Processing Time",
        value: "3.2 days",
        change: "-0.5",
        trend: "up",
        icon: TrendingUp,
        description: "Faster processing",
    },
];

export const onboardingData: OnboardingApplication[] = [
    {
        id: "ONB-001",
        applicantName: "Arjun Patel",
        businessName: "Tasty Bites Cafe",
        businessType: "restaurant",
        location: "Sector 62, Noida",
        city: "Noida",
        applicationDate: "2024-12-20",
        status: "pending",
        assignedTo: "Unassigned",
        phone: "+91 98765 11111",
        email: "arjun@tastybites.com",
        documents: 3,
    },
    {
        id: "ONB-002",
        applicantName: "Meera Singh",
        businessName: "Green Valley Grocers",
        businessType: "grocery",
        location: "Lajpat Nagar, Delhi",
        city: "Delhi",
        applicationDate: "2024-12-18",
        status: "in-review",
        assignedTo: "Rahul Sharma",
        phone: "+91 98765 22222",
        email: "meera@greenvalley.com",
        documents: 5,
    },
    {
        id: "ONB-003",
        applicantName: "Dr. Karan Malhotra",
        businessName: "LifeCare Pharmacy",
        businessType: "pharmacy",
        location: "Vasant Kunj, Delhi",
        city: "Delhi",
        applicationDate: "2024-12-15",
        status: "approved",
        assignedTo: "Priya Patel",
        phone: "+91 98765 33333",
        email: "karan@lifecare.com",
        documents: 6,
    },
    {
        id: "ONB-004",
        applicantName: "Simran Kaur",
        businessName: "Style Studio",
        businessType: "retail",
        location: "Rajouri Garden, Delhi",
        city: "Delhi",
        applicationDate: "2024-12-22",
        status: "pending",
        assignedTo: "Unassigned",
        phone: "+91 98765 44444",
        email: "simran@stylestudio.com",
        documents: 2,
    },
    {
        id: "ONB-005",
        applicantName: "Rohit Verma",
        businessName: "Quick Bites",
        businessType: "restaurant",
        location: "Indirapuram, Ghaziabad",
        city: "Ghaziabad",
        applicationDate: "2024-12-19",
        status: "in-review",
        assignedTo: "Amit Kumar",
        phone: "+91 98765 55555",
        email: "rohit@quickbites.com",
        documents: 4,
    },
    {
        id: "ONB-006",
        applicantName: "Anjali Reddy",
        businessName: "Fresh Harvest",
        businessType: "grocery",
        location: "Mayur Vihar, Delhi",
        city: "Delhi",
        applicationDate: "2024-12-17",
        status: "rejected",
        assignedTo: "Sneha Desai",
        phone: "+91 98765 66666",
        email: "anjali@freshharvest.com",
        documents: 3,
    },
];
