import { BulkShipment } from "./types";

export const bulkShipmentsData: BulkShipment[] = [
  {
    id: "BULK-001",
    name: "December E-commerce Batch",
    status: "processing",
    totalShipments: 250,
    processed: 187,
    failed: 3,
    createdBy: "Aqib Khan",
    createdAt: "2024-12-11 09:30",
    updatedAt: "2024-12-11 14:45",
    template: "E-commerce Standard",
    serviceType: "Surface",
    paymentType: "Prepaid",
    awbPrefix: "HJD2924",
    progress: 75,
    shipments: [
      {
        id: "SH-001",
        awbNumber: "HJD292412600",
        status: "processed",
        sender: {
          name: "Aqib",
          phone: "8601677140",
          address: "123 MG Road",
          city: "Delhi",
          pincode: "110094",
        },
        receiver: {
          name: "Customer One",
          phone: "9876543210",
          address: "45 Park Street",
          city: "Bangalore",
          pincode: "560001",
        },
        package: {
          type: "Parcel",
          weight: "2.5 kg",
          description: "Mobile Accessories",
          codAmount: "₹0",
        },
        service: {
          type: "Surface",
          payment: "Prepaid",
        },
      },
      {
        id: "SH-002",
        awbNumber: "HJD292412601",
        status: "processed",
        sender: {
          name: "Aqib",
          phone: "8601677140",
          address: "123 MG Road",
          city: "Delhi",
          pincode: "110094",
        },
        receiver: {
          name: "Customer Two",
          phone: "9876543211",
          address: "78 Electronics City",
          city: "Hyderabad",
          pincode: "500001",
        },
        package: {
          type: "Parcel",
          weight: "1.8 kg",
          description: "Books",
          codAmount: "₹0",
        },
        service: {
          type: "Surface",
          payment: "Prepaid",
        },
      },
    ],
  },
  {
    id: "BULK-002",
    name: "Black Friday Sale Orders",
    status: "completed",
    totalShipments: 500,
    processed: 500,
    failed: 0,
    createdBy: "Rajesh Kumar",
    createdAt: "2024-12-10 08:15",
    updatedAt: "2024-12-10 18:30",
    template: "Festive Sale",
    serviceType: "Air",
    paymentType: "COD",
    awbPrefix: "HJD2923",
    progress: 100,
    shipments: [],
  },
  {
    id: "BULK-003",
    name: "Corporate Dispatch - Tech Solutions",
    status: "draft",
    totalShipments: 75,
    processed: 0,
    failed: 0,
    createdBy: "Priya Singh",
    createdAt: "2024-12-11 11:20",
    updatedAt: "2024-12-11 11:20",
    template: "Corporate Standard",
    serviceType: "Express",
    paymentType: "Credit",
    awbPrefix: "HJD2924",
    progress: 0,
    shipments: [],
  },
  {
    id: "BULK-004",
    name: "Warehouse Clearance Batch",
    status: "processing",
    totalShipments: 120,
    processed: 45,
    failed: 2,
    createdBy: "Amit Sharma",
    createdAt: "2024-12-11 10:00",
    updatedAt: "2024-12-11 13:15",
    template: "Clearance Sale",
    serviceType: "Surface",
    paymentType: "Mixed",
    awbPrefix: "HJD2924",
    progress: 38,
    shipments: [],
  },
  {
    id: "BULK-005",
    name: "International Export Batch",
    status: "failed",
    totalShipments: 50,
    processed: 12,
    failed: 38,
    createdBy: "Global Exports",
    createdAt: "2024-12-11 08:45",
    updatedAt: "2024-12-11 12:00",
    template: "International",
    serviceType: "Air",
    paymentType: "Prepaid",
    awbPrefix: "HJD2924",
    progress: 24,
    shipments: [],
  },
];
