import { InventoryItem, InventoryStat } from "./types";
import { Package, AlertTriangle, XCircle, IndianRupee } from "lucide-react";

export const inventoryStats: InventoryStat[] = [
    {
        title: "Total Items",
        value: "1,247",
        change: "+12",
        trend: "up",
        icon: Package,
        description: "Active SKUs",
    },
    {
        title: "Low Stock Alerts",
        value: "23",
        change: "+5",
        trend: "down",
        icon: AlertTriangle,
        description: "Needs restock",
    },
    {
        title: "Out of Stock",
        value: "8",
        change: "-2",
        trend: "up",
        icon: XCircle,
        description: "Urgent action",
    },
    {
        title: "Total Value",
        value: "₹45.2L",
        change: "+8.5%",
        trend: "up",
        icon: IndianRupee,
        description: "Inventory worth",
    },
];

export const inventoryData: InventoryItem[] = [
    {
        id: "INV-001",
        name: "Delivery Bags - Large",
        sku: "DB-LRG-001",
        category: "Packaging",
        currentStock: 450,
        minStock: 200,
        maxStock: 1000,
        unitPrice: 45,
        totalValue: 20250,
        status: "in-stock",
        lastUpdated: "2024-12-23",
        supplier: "PackPro Industries",
        location: "Warehouse A - Shelf 12",
    },
    {
        id: "INV-002",
        name: "Thermal Labels (Roll)",
        sku: "TL-100-002",
        category: "Supplies",
        currentStock: 85,
        minStock: 100,
        maxStock: 500,
        unitPrice: 120,
        totalValue: 10200,
        status: "low-stock",
        lastUpdated: "2024-12-22",
        supplier: "Label Solutions Ltd",
        location: "Warehouse A - Shelf 5",
    },
    {
        id: "INV-003",
        name: "Handheld Scanners",
        sku: "HS-PRO-003",
        category: "Equipment",
        currentStock: 0,
        minStock: 10,
        maxStock: 50,
        unitPrice: 8500,
        totalValue: 0,
        status: "out-of-stock",
        lastUpdated: "2024-12-20",
        supplier: "TechGear Supplies",
        location: "Warehouse B - Equipment Room",
    },
    {
        id: "INV-004",
        name: "Packing Tape - Heavy Duty",
        sku: "PT-HD-004",
        category: "Packaging",
        currentStock: 320,
        minStock: 150,
        maxStock: 800,
        unitPrice: 25,
        totalValue: 8000,
        status: "in-stock",
        lastUpdated: "2024-12-23",
        supplier: "PackPro Industries",
        location: "Warehouse A - Shelf 8",
    },
    {
        id: "INV-005",
        name: "Safety Vests",
        sku: "SV-STD-005",
        category: "Safety",
        currentStock: 42,
        minStock: 50,
        maxStock: 200,
        unitPrice: 180,
        totalValue: 7560,
        status: "low-stock",
        lastUpdated: "2024-12-21",
        supplier: "SafeWork Solutions",
        location: "Warehouse C - Safety Storage",
    },
    {
        id: "INV-006",
        name: "Delivery Boxes - Medium",
        sku: "DB-MED-006",
        category: "Packaging",
        currentStock: 680,
        minStock: 300,
        maxStock: 1500,
        unitPrice: 35,
        totalValue: 23800,
        status: "in-stock",
        lastUpdated: "2024-12-23",
        supplier: "BoxMart Inc",
        location: "Warehouse A - Shelf 15",
    },
    {
        id: "INV-007",
        name: "Bubble Wrap (Roll)",
        sku: "BW-50M-007",
        category: "Packaging",
        currentStock: 125,
        minStock: 80,
        maxStock: 400,
        unitPrice: 95,
        totalValue: 11875,
        status: "in-stock",
        lastUpdated: "2024-12-22",
        supplier: "PackPro Industries",
        location: "Warehouse A - Shelf 10",
    },
    {
        id: "INV-008",
        name: "Forklift Battery",
        sku: "FB-48V-008",
        category: "Equipment",
        currentStock: 0,
        minStock: 5,
        maxStock: 20,
        unitPrice: 15000,
        totalValue: 0,
        status: "out-of-stock",
        lastUpdated: "2024-12-18",
        supplier: "PowerCell Distributors",
        location: "Warehouse B - Battery Storage",
    },
    {
        id: "INV-009",
        name: "Stretch Film",
        sku: "SF-IND-009",
        category: "Packaging",
        currentStock: 210,
        minStock: 100,
        maxStock: 600,
        unitPrice: 65,
        totalValue: 13650,
        status: "in-stock",
        lastUpdated: "2024-12-23",
        supplier: "PackPro Industries",
        location: "Warehouse A - Shelf 7",
    },
    {
        id: "INV-010",
        name: "First Aid Kits",
        sku: "FAK-PRO-010",
        category: "Safety",
        currentStock: 18,
        minStock: 25,
        maxStock: 100,
        unitPrice: 450,
        totalValue: 8100,
        status: "low-stock",
        lastUpdated: "2024-12-20",
        supplier: "MediSupply Co",
        location: "Warehouse C - Safety Storage",
    },
];
