// components/master/products/mockData.ts
import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    sku: "SKU0001",
    name: "iPhone 15 Pro Max",
    description: "Latest Apple smartphone with advanced camera features",
    category: "Electronics",
    subCategory: "Mobile Phones",
    hsnCode: "85171200",
    weight: 0.221,
    dimensions: "16.0 x 7.8 x 0.8 cm",
    value: 129999,
    fragile: true,
    hazardous: false,
    temperatureSensitive: true,
    specialHandling: "Handle with care, avoid moisture",
    storageRequirements: "Store in dry place, avoid direct sunlight",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-11T08:30:00Z",
  },
  {
    id: "2",
    sku: "SKU0002",
    name: 'Samsung 55" 4K Smart TV',
    description: "Ultra HD Smart Television with Quantum Dot Technology",
    category: "Electronics",
    subCategory: "Televisions",
    hsnCode: "85287200",
    weight: 18.5,
    dimensions: "123.0 x 71.0 x 28.0 cm",
    value: 64999,
    fragile: true,
    hazardous: false,
    temperatureSensitive: false,
    specialHandling: "Keep upright, fragile screen",
    storageRequirements: "Store in original packaging",
    status: "active",
    createdAt: "2024-02-20T14:30:00Z",
    updatedAt: "2024-12-11T09:15:00Z",
  },
  {
    id: "3",
    sku: "SKU0003",
    name: "Laptop Cooling Pad",
    description: "USB powered laptop cooling pad with adjustable fans",
    category: "Electronics",
    subCategory: "Computer Accessories",
    hsnCode: "84733090",
    weight: 0.85,
    dimensions: "35.0 x 25.0 x 3.0 cm",
    value: 2499,
    fragile: false,
    hazardous: false,
    temperatureSensitive: false,
    specialHandling: "Standard handling",
    storageRequirements: "Store in dry conditions",
    status: "active",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-12-10T16:45:00Z",
  },
  {
    id: "4",
    sku: "SKU0004",
    name: "Perfume Gift Set",
    description: "Luxury perfume collection with 3 different fragrances",
    category: "Beauty & Personal Care",
    subCategory: "Fragrances",
    hsnCode: "33030010",
    weight: 0.45,
    dimensions: "15.0 x 10.0 x 8.0 cm",
    value: 5999,
    fragile: true,
    hazardous: true,
    temperatureSensitive: true,
    specialHandling: "Fragile, contains flammable liquids",
    storageRequirements: "Store in cool place, away from heat sources",
    status: "active",
    createdAt: "2024-04-05T11:00:00Z",
    updatedAt: "2024-12-11T10:20:00Z",
  },
  {
    id: "5",
    sku: "SKU0005",
    name: "Designer Leather Handbag",
    description: "Premium genuine leather handbag with multiple compartments",
    category: "Fashion",
    subCategory: "Bags & Luggage",
    hsnCode: "42022190",
    weight: 1.2,
    dimensions: "30.0 x 20.0 x 15.0 cm",
    value: 18999,
    fragile: false,
    hazardous: false,
    temperatureSensitive: false,
    specialHandling: "Keep in dust bag, avoid moisture",
    storageRequirements: "Store in dry place",
    status: "active",
    createdAt: "2024-05-15T13:00:00Z",
    updatedAt: "2024-12-11T11:30:00Z",
  },
  {
    id: "6",
    sku: "SKU0006",
    name: "Protein Powder Supplement",
    description: "Whey protein powder for muscle building and recovery",
    category: "Health & Nutrition",
    subCategory: "Supplements",
    hsnCode: "21069099",
    weight: 2.0,
    dimensions: "25.0 x 15.0 x 15.0 cm",
    value: 3499,
    fragile: false,
    hazardous: false,
    temperatureSensitive: true,
    specialHandling: "Keep sealed, avoid moisture",
    storageRequirements: "Store in cool dry place",
    status: "inactive",
    createdAt: "2024-06-20T15:00:00Z",
    updatedAt: "2024-12-10T14:15:00Z",
  },
  {
    id: "7",
    sku: "SKU0007",
    name: "Lithium-ion Power Bank",
    description: "20000mAh fast charging power bank with multiple ports",
    category: "Electronics",
    subCategory: "Mobile Accessories",
    hsnCode: "85076000",
    weight: 0.45,
    dimensions: "15.0 x 7.0 x 2.5 cm",
    value: 2999,
    fragile: true,
    hazardous: true,
    temperatureSensitive: true,
    specialHandling: "Contains lithium battery, handle with care",
    storageRequirements: "Store in cool place, avoid direct sunlight",
    status: "active",
    createdAt: "2024-07-12T08:00:00Z",
    updatedAt: "2024-12-11T12:00:00Z",
  },
  {
    id: "8",
    sku: "SKU0008",
    name: "Ceramic Dinner Set",
    description: "16-piece ceramic dinner set with modern design",
    category: "Home & Kitchen",
    subCategory: "Kitchenware",
    hsnCode: "69111010",
    weight: 8.5,
    dimensions: "45.0 x 35.0 x 25.0 cm",
    value: 7999,
    fragile: true,
    hazardous: false,
    temperatureSensitive: false,
    specialHandling: "Extremely fragile, handle with extreme care",
    storageRequirements: "Store in padded packaging",
    status: "active",
    createdAt: "2024-08-08T10:30:00Z",
    updatedAt: "2024-12-11T13:45:00Z",
  },
  {
    id: "9",
    sku: "SKU0009",
    name: "Frozen Seafood Pack",
    description: "Assorted frozen seafood including shrimp and fish fillets",
    category: "Food & Beverages",
    subCategory: "Frozen Foods",
    hsnCode: "03061700",
    weight: 2.5,
    dimensions: "30.0 x 20.0 x 10.0 cm",
    value: 2499,
    fragile: false,
    hazardous: false,
    temperatureSensitive: true,
    specialHandling: "Requires frozen storage, time-sensitive delivery",
    storageRequirements: "Store at -18°C or below",
    status: "active",
    createdAt: "2024-09-25T14:00:00Z",
    updatedAt: "2024-12-11T14:20:00Z",
  },
  {
    id: "10",
    sku: "SKU0010",
    name: "LED Desk Lamp",
    description: "Adjustable LED desk lamp with touch controls",
    category: "Home & Kitchen",
    subCategory: "Lighting",
    hsnCode: "94052000",
    weight: 1.1,
    dimensions: "35.0 x 15.0 x 8.0 cm",
    value: 1899,
    fragile: true,
    hazardous: false,
    temperatureSensitive: false,
    specialHandling: "Fragile glass components",
    storageRequirements: "Store in original packaging",
    status: "inactive",
    createdAt: "2024-10-30T16:00:00Z",
    updatedAt: "2024-12-10T17:30:00Z",
  },
];
