import { Route } from "./types";

export const mockRoutes: Route[] = [
  {
    id: "R001",
    code: "BOM-DEL-L1",
    sourceCity: "Mumbai",
    destinationCity: "Delhi",
    sourceHub: "Mumbai Gateway",
    destinationHub: "Delhi Hub",
    distanceKm: 1400,
    transitTimeHours: 36,
    stops: ["Surat Hub", "Jaipur Hub"],
    status: "ACTIVE",
    type: "LINEHAUL",
    isReturnRoute: true,
    baseCost: 25000,
  },
  {
    id: "R002",
    code: "BLR-CHE-L1",
    sourceCity: "Bangalore",
    destinationCity: "Chennai",
    sourceHub: "Bangalore Hub",
    destinationHub: "Chennai Hub",
    distanceKm: 350,
    transitTimeHours: 8,
    stops: ["Hosur"],
    status: "ACTIVE",
    type: "LINEHAUL",
    isReturnRoute: true,
    baseCost: 5000,
  },
  {
    id: "R003",
    code: "BOM-PUN-F1",
    sourceCity: "Mumbai",
    destinationCity: "Pune",
    sourceHub: "Mumbai Gateway",
    destinationHub: "Pune Branch",
    distanceKm: 150,
    transitTimeHours: 4,
    stops: ["Navi Mumbai"],
    status: "ACTIVE",
    type: "FEEDER",
    isReturnRoute: true,
    baseCost: 2000,
  },
  {
    id: "R004",
    code: "DEL-GGN-LM1",
    sourceCity: "Delhi",
    destinationCity: "Gurgaon",
    sourceHub: "Delhi Hub",
    destinationHub: "Gurgaon DC",
    distanceKm: 40,
    transitTimeHours: 2,
    stops: [],
    status: "ACTIVE",
    type: "LAST_MILE",
    isReturnRoute: false,
    baseCost: 500,
  },
  {
    id: "R005",
    code: "KOL-BOM-L2",
    sourceCity: "Kolkata",
    destinationCity: "Mumbai",
    sourceHub: "Kolkata Hub",
    destinationHub: "Mumbai Gateway",
    distanceKm: 2000,
    transitTimeHours: 48,
    stops: ["Nagpur Hub"],
    status: "BLOCKED",
    type: "LINEHAUL",
    isReturnRoute: false,
    baseCost: 40000,
  }
];
