import { User, Branch } from "./types";

export const branches: Branch[] = [
  {
    id: "BR-001",
    name: "Mumbai Central Hub",
    code: "MUM-CENT",
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    id: "BR-002",
    name: "Delhi North Branch",
    code: "DEL-NORTH",
    city: "Delhi",
    state: "Delhi",
  },
  {
    id: "BR-003",
    name: "Bangalore South",
    code: "BLR-SOUTH",
    city: "Bangalore",
    state: "Karnataka",
  },
  {
    id: "BR-004",
    name: "Chennai Central",
    code: "CHN-CENT",
    city: "Chennai",
    state: "Tamil Nadu",
  },
  {
    id: "BR-005",
    name: "Kolkata East",
    code: "KOL-EAST",
    city: "Kolkata",
    state: "West Bengal",
  },
];

export const users: User[] = [
  {
    id: "USR-001",
    email: "admin@speedylogistics.com",
    name: "Super Admin",
    role: "superadmin",
    status: "active",
    createdAt: "2024-01-01",
    lastLogin: "2024-12-11",
    phone: "+91 9876543210",
  },
  {
    id: "USR-002",
    email: "mumbai.manager@speedylogistics.com",
    name: "Rajesh Kumar",
    role: "branch",
    branchId: "BR-001",
    branchName: "Mumbai Central Hub",
    status: "active",
    createdAt: "2024-01-15",
    lastLogin: "2024-12-10",
    phone: "+91 9876543211",
  },
  {
    id: "USR-003",
    email: "delhi.dispatcher@speedylogistics.com",
    name: "Priya Singh",
    role: "dispatcher",
    branchId: "BR-002",
    branchName: "Delhi North Branch",
    status: "active",
    createdAt: "2024-02-01",
    lastLogin: "2024-12-11",
    phone: "+91 9876543212",
  },
  {
    id: "USR-004",
    email: "rider.amit@speedylogistics.com",
    name: "Amit Sharma",
    role: "rider",
    branchId: "BR-001",
    branchName: "Mumbai Central Hub",
    status: "active",
    createdAt: "2024-02-15",
    lastLogin: "2024-12-10",
    phone: "+91 9876543213",
  },
  {
    id: "USR-005",
    email: "customer@example.com",
    name: "Customer User",
    role: "customer",
    status: "active",
    createdAt: "2024-03-01",
    lastLogin: "2024-12-09",
    phone: "+91 9876543214",
  },
  {
    id: "USR-006",
    email: "partner@logistics.com",
    name: "Logistics Partner",
    role: "partner",
    status: "pending",
    createdAt: "2024-03-15",
    phone: "+91 9876543215",
  },
];
