import { RiderPerformance } from "./types";

export const mockPerformance: RiderPerformance[] = [
    {
        id: "P-001",
        name: "Vikram Singh",
        riderId: "RS-1001",
        totalDeliveries: 450,
        onTimeDeliveryPct: 98,
        avgRating: 4.9,
        cancellationRate: 0.5,
        avgDeliveryTime: "22 mins",
        earnings: 25000,
        incentives: 5000,
        complaints: 0,
        status: "excellent",
    },
    {
        id: "P-002",
        name: "Amit Kumar",
        riderId: "RS-1002",
        totalDeliveries: 380,
        onTimeDeliveryPct: 92,
        avgRating: 4.5,
        cancellationRate: 1.2,
        avgDeliveryTime: "28 mins",
        earnings: 21000,
        incentives: 2000,
        complaints: 2,
        status: "good",
    },
    {
        id: "P-003",
        name: "Rahul Sharma",
        riderId: "RS-1003",
        totalDeliveries: 500,
        onTimeDeliveryPct: 99,
        avgRating: 5.0,
        cancellationRate: 0.0,
        avgDeliveryTime: "18 mins",
        earnings: 30000,
        incentives: 8000,
        complaints: 0,
        status: "excellent",
    },
    {
        id: "P-004",
        name: "Suresh Patel",
        riderId: "RS-1004",
        totalDeliveries: 200,
        onTimeDeliveryPct: 85,
        avgRating: 4.1,
        cancellationRate: 3.5,
        avgDeliveryTime: "35 mins",
        earnings: 12000,
        incentives: 0,
        complaints: 5,
        status: "average",
    },
    {
        id: "P-005",
        name: "Deepak Verma",
        riderId: "RS-1005",
        totalDeliveries: 150,
        onTimeDeliveryPct: 78,
        avgRating: 3.8,
        cancellationRate: 5.0,
        avgDeliveryTime: "40 mins",
        earnings: 9000,
        incentives: 0,
        complaints: 8,
        status: "poor",
    },
];
